# Generated by Django 4.2.11 on 2024-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0004_transitionmeta_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("username_column", "Username Column"),
                            ("database_visibility", "Database Visibility"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
