# Generated by Django 4.2.11 on 2024-06-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0005_featuresetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresetting",
            name="feature",
            field=models.CharField(
                choices=[
                    ("username_column", "Username Column"),
                    ("database_visibility", "Database Visibility"),
                    ("transition_history_display", "Transition History Display"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
