# Generated by Django 4.2.11 on 2024-06-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("river", "0006_alter_featuresetting_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
    ]
