# Generated by Django 4.1.9 on 2025-01-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0007_workflow_description_workflow_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureSetting',
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together=set(),
        ),
    ]
