# Generated by Django 4.1.13 on 2025-01-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("river", "0008_delete_featuresetting_alter_workflow_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitionapprovalmeta",
            name="permissions",
        ),
    ]
